name: CI

on: [push, pull_request]

jobs:
  build_ubuntu_22:
    runs-on: ubuntu-latest
    container: ubuntu:jammy-20220531

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt install -y g++
          apt install -y cmake extra-cmake-modules gettext libfmt-dev
          apt install -y libglib2.0-dev
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_TEST=On
          make -j
          cd ../
          mkdir -p src/Engine/build
          cd src/Engine/build
          cmake ../
          make -j
      - name: Test
        run: |
          cd build
          make runTest runGramambular2Test
          cd ../src/Engine/build
          make runMcBopomofoLMLibTest
      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build/

  build_ubuntu_20:
    runs-on: ubuntu-latest
    container: ubuntu:focal-20220531

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt install -y g++
          apt install -y cmake extra-cmake-modules gettext libfmt-dev
          apt install -y libglib2.0-dev
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_TEST=On
          make -j
      - name: Test
        run: |
          cd build
          make runTest
      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build/
